[package]
name = "example-routing"
version = "0.0.0"
edition = "2018"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "example_routing"
path = "src/main.rs"
doc = false

[dependencies]
tsukuyomi = "0.5.0"
tsukuyomi-server = "0.2.0"
