[package]
name = "example-tls"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "tls"
path = "src/main.rs"
doc = false

[dependencies]
tsukuyomi = { version = "0.4.0-dev", features = ["tls"] }
rustls = "0.14"
failure = "0.1.3"

