version: "{build}"

branches:
 only:
   - master

environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      TOOLCHAIN: stable
    - TARGET: x86_64-pc-windows-msvc
      TOOLCHAIN: beta
    - TARGET: x86_64-pc-windows-msvc
      TOOLCHAIN: nightly

matrix:
  allow_failures:
   - TOOLCHAIN: nightly

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %TOOLCHAIN%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - set RUST_TEST_THREADS=1
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo clean
  - cargo test --all
