version: "{build}"

branches:
  only:
    - master
    - /^\d+\.\d+$/

environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      TOOLCHAIN: stable
    - TARGET: x86_64-pc-windows-msvc
      TOOLCHAIN: beta
    - TARGET: x86_64-pc-windows-msvc
      TOOLCHAIN: nightly

matrix:
  allow_failures:
   - TOOLCHAIN: nightly

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %TOOLCHAIN%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - set RUST_TEST_THREADS=1
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo clean
  - cargo test
  - cargo test --no-default-features
  #- if [%TOOLCHAIN%]==[nightly] (
  #    cargo test --features nightly
  #  )
  - if [%TOOLCHAIN%]==[nightly] (
      cargo test -p tsukuyomi-codegen
    )
  # contrib
  - cargo test -p tsukuyomi-juniper
  - if [%TOOLCHAIN%]==[nightly] (
      cargo test -p doctest
    )
  # FIXME: move examples to independent repository.
  - cargo test -p example-basic
  # - cargo test -p example-diesel
  - cargo test -p example-json
  - cargo test -p example-lines
  - cargo test -p example-routing
  # - cargo test -p unix-socket
  - if [%TOOLCHAIN%]==[nightly] (
      cargo test -p example-async-await
    )
  - if [%TOOLCHAIN%]==[nightly] (
      cargo test -p example-git-server
    )
