[package]
name = "example-staticfile"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "example_staticfile"
path = "src/main.rs"
doc = false

[dependencies]
tsukuyomi = "0.4.0-dev"
