[package]
name = "basic"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "basic"
path = "src/main.rs"
doc = false

[dependencies]
tsukuyomi = { path = "../.." }
pretty_env_logger = "0.2.3"
